/*
 * Generated by /Users/davidcoplowe/software/xsLLhFitter/cmake/CMAKE/Darwin/cmake-3.5.0/bootstrap
 * Version:     $Revision$
 *
 * Source directory: /Users/davidcoplowe/software/xsLLhFitter/cmake/CMAKE/Darwin/cmake-3.5.0
 * Binary directory: /Users/davidcoplowe/software/xsLLhFitter/cmake/CMAKE/Darwin/cmake-3.5.0/Bootstrap.cmk
 *
 * C compiler:   gcc
 * C flags:      
 *
 * C++ compiler: g++
 * C++ flags:    
 *
 * Make:         make
 *
 * Sources:
 *   cmake    cmakemain   cmcmd    cmCommandArgumentLexer   cmCommandArgumentParser   cmCommandArgumentParserHelper   cmCommonTargetGenerator   cmCPackPropertiesGenerator   cmDefinitions   cmDepends   cmDependsC   cmDocumentationFormatter   cmPolicies   cmProperty   cmPropertyMap   cmPropertyDefinition   cmPropertyDefinitionMap   cmMakefile   cmExportBuildFileGenerator   cmExportFileGenerator   cmExportInstallFileGenerator   cmExportTryCompileFileGenerator   cmExportSet   cmExportSetMap   cmExternalMakefileProjectGenerator   cmGeneratorExpressionEvaluationFile   cmGeneratedFileStream   cmGeneratorTarget   cmGeneratorExpressionContext   cmGeneratorExpressionDAGChecker   cmGeneratorExpressionEvaluator   cmGeneratorExpressionLexer   cmGeneratorExpressionNode   cmGeneratorExpressionParser   cmGeneratorExpression   cmGlobalCommonGenerator   cmGlobalGenerator   cmInstallDirectoryGenerator   cmLocalCommonGenerator   cmLocalGenerator   cmInstalledFile   cmInstallGenerator   cmInstallExportGenerator   cmInstallFilesGenerator   cmInstallScriptGenerator   cmInstallTargetGenerator   cmScriptGenerator   cmSourceFile   cmSourceFileLocation   cmState   cmSystemTools   cmTestGenerator   cmVersion   cmFileTimeComparison   cmGlobalUnixMakefileGenerator3   cmLocalUnixMakefileGenerator3   cmMakefileExecutableTargetGenerator   cmMakefileLibraryTargetGenerator   cmMakefileTargetGenerator   cmMakefileUtilityTargetGenerator   cmOutputConverter   cmOSXBundleGenerator   cmNewLineStyle   cmBootstrapCommands1   cmBootstrapCommands2   cmCommandsForBootstrap   cmTarget   cmTest   cmCustomCommand   cmCustomCommandGenerator   cmCacheManager   cmListFileCache   cmComputeLinkDepends   cmComputeLinkInformation   cmOrderDirectories   cmComputeTargetDepends   cmComputeComponentGraph   cmExprLexer   cmExprParser   cmExprParserHelper    cmListFileLexer   
 * kwSys Sources:
 *   Directory   EncodingCXX   FStream   Glob   RegularExpression   SystemTools     EncodingC     ProcessUNIX     String     System     Terminal
 */

#define CMAKE_BOOTSTRAP_SOURCE_DIR "/Users/davidcoplowe/software/xsLLhFitter/cmake/CMAKE/Darwin/cmake-3.5.0"
#define CMAKE_BOOTSTRAP_BINARY_DIR "/Users/davidcoplowe/software/xsLLhFitter/cmake/CMAKE/Darwin/cmake-3.5.0"
#define CMAKE_DATA_DIR "/bootstrap-not-insalled"
#define CMAKE_BOOTSTRAP
